version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend.fixed
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mysql+pymysql://interviewpro:your_password@mysql:3306/interviewpro
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=your_jwt_secret_key_here
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/instance:/app/instance
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
